version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/leboncoin-clone
      - PORT=8081
      - JWT_SECRET=your_jwt_secret
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
